### PR TITLE
Flakeify node2nix

### PR DESCRIPTION
**Pull request by samuelludwig**
Add a `flake.nix` and `flake.lock` file so that `node2nix` can be used/addressed as a Nix Flake.

### CODE REVIEW

**Review by mkg20001 — APPROVED** [review]

**Comment by tv42** [comment]
This was approved almost 4 months ago, but never merged? *friendly nudge*

**Comment by svanderburg** [comment]
It's fine to add a flake, but be aware that I until it has become a mainstream Nix feature, I won't be providing much support for it myself.

**Comment by samuelludwig** [comment]
I apologize, I'm not super up-to-date with everything, but from my understanding Flakes are no longer "experimental" (whatever that *actually* means for Nix-things)?

To be honest however, I've been taking a bit of a sabbatical from Nix myself, as I explore some other horizons. I think I'll likely come back, but I need some time to travel. However, that means that I'm really no longer any good authority on anything Nix (including anything I've written). I still think Flakes are one of Nix's most important features, and would hope to see them used/provided/refined more, but I can't claim to hold any stock in the process at the moment.

**Comment by FRidh** [comment]
> I apologize, I'm not super up-to-date with everything, but from my understanding Flakes are no longer "experimental" (whatever that actually means for Nix-things)?

Yes they are still experimental.

Regardless, I'd love to see this in as well.

**Comment by svanderburg** [comment]
Ok I've attended Eelco's last talk and since he confirmed that flakes will go mainstream soon and no controversial changes are expected, I'll integrate this.

**Pull request merged**
