### PR TITLE
Filter optional dependencies from parsed package-lock.json

### LINKED ISSUE #73: Truly optional optionalDependencies can be broken
Currently, node2nix treats optionalDependencies just like dependencies, but it's not unheard of for packages to have optionalDependencies which cannot be built on all platforms.  For example, [see the apollo engine](https://github.com/apollographql/apollo-engine-js/blob/master/package.json#L29-L33).  The generated nix files for packages such as that require editing before they will build appropriately. 

The npm docs say:
> If a dependency can be used, but you would like npm to proceed if it cannot be found or fails to install, then you may put it in the optionalDependencies object.

I assume that logic cannot be duplicated in nix.  What if optional dependencies were not included by default, but node2nix had an argument `--optional-dependencies name1[,name2,...]`?

### PR DESCRIPTION
**Pull request by nicknovitski**
e: I thought this would fix an issue I had encountered, but I was wrong.

### CODE REVIEW

**Comment by nicknovitski** [comment]
Ah, I suppose we'd also want to conditionally filter those with `"dev": true`?

**Comment by nicknovitski** [comment]
Looking at more package-lock files, it seems like this code would have to be recursive.  That is, the files have a top level `dependencies` key whose value is an object, and the values of that object usually also have a `dependencies` key, whose values are objects that might have `dev` or `optional` keys.

**Comment by nicknovitski** [comment]
I changed my code to filter recursively.

**Comment by svanderburg** [comment]
@nicknovitski I need to take a closer look at your changes -- they make sense, but maybe we have to put your changes in different places in the code. I'll need a bit of time to review and experiment.

**Comment by svanderburg** [comment]
I implemented my own change in revision 3033bf410be0e8cca12df4e675263c7415d6d977. Earlier, I also implemented functionality that strips out bundled dependencies. I think this check should also belong there.

Give it a try and see if it works for you.

**Comment by nicknovitski** [comment]
It does, thank you!

**Pull request closed without merging**
