### PR TITLE
Add support for node 7

### PR DESCRIPTION
**Pull request by shosti**
There are some npm packages that require it.

### CODE REVIEW

**Comment by grahamc** [comment]
Same, but for node 8? Do you need help with this project, @svanderburg?

**Comment by svanderburg** [comment]
@grahamc Yes node.js 8 support should also be added, but there are a bunch of incompatibilities with the npm that comes with it.

Today I have started investigating.

**Comment by copumpkin** [comment]
Added a ticket to track 8 at #55

**Comment by jammerful** [comment]
@svanderburg node.js v7 reached end of life, and more importantly was removed from the nixpkgs repo a few months ago, so the defautl.nix that node2nix generates throws an error that the package nodejs-7_x does not exist. Please see my PR which removes support for it: https://github.com/svanderburg/node2nix/pull/57

**Pull request merged**
