### PR TITLE
add support for nodejs v6

### PR DESCRIPTION
**Pull request by cko**

### CODE REVIEW

**Comment by svanderburg** [comment]
Adding a -6 option is a good idea, since Node.js 6.x is now the mainstream LTS version.

However, for the tests, it is not needed to generate node-packages-v6.nix. Since the generation process for v5 and v6 is the same, it would be better to reuse these expressions among the v5 and v6 testcases.

Could you revise your commit in such a way that the generated node-packages.nix is shared among v5 or v6?

Or alternatively, can you remove the generated tests? Then I will modify the bootstrap script myself in such a way that the generated v5 and v6 expressions are shared. This should be relatively simple for me to accomplish.

**Comment by cko** [comment]
What about removing the `-5` option as there is no LTS for nodejs v5 anyway (see: https://github.com/nodejs/LTS)?

**Comment by svanderburg** [comment]
My employer still relies on having v5 around. Not that I personally have anything against its removal, but they partially fund my work. so... :)

**Comment by svanderburg** [comment]
Ok good! If you could also squash your two commits to get rid of all the obsolete code churn (adding + removing node-packages-v5.nix are many lines of code), then it's ready to be merged.

**Comment by cko** [comment]
[x] done

**Pull request merged**
