### PR TITLE
utillinux -> util-linux

### LINKED ISSUE #213: Update utillinux to util-linux
In https://github.com/NixOS/nixpkgs/pull/104776/ `utllinux` was renamed to `util-linux`.

On nixos unstable this leads to the following error when trying to build the package:

```
error: anonymous function at ./pkgs/development/node-packages/node-env.nix:3:1 called without required argument 'util-linux', at ./pkgs/servers/zigbee2mqtt/node.nix:8:13
```

Replacing `utillinux` as described fixes that.

### PR DESCRIPTION
**Pull request by SuperSandro2000**
https://github.com/NixOS/nixpkgs/pull/104776

Closes #213 for master

I know that this wont work on stable but I would like to patch this in unstable to not break nixpkgs when regenerating nodePackages.

### CODE REVIEW

**Comment by svanderburg** [comment]
I think we need to give this some more thought -- while this PR indeed fixes the situation in the current Nixpkgs master branch, it is somewhat impractical to no longer support the latest stable Nixpkgs.

I'm close to a new release of node2nix, but I prefer that it remains compatible with both the stable version as well as master. For most production deployments that I support, I typically use the latest stable version of Nixpkgs, not master because it is typically breaking a lot of things.

The alternative is that we need to ship two kinds of versions of node2nix: one that works with the latest stable and one with the latest master, but I'm not in favor of doing that, because it causes confusion to end-users.

**Comment by svanderburg** [comment]
I'm now working on a fix myself

**Comment by svanderburg** [comment]
I have implemented a backwards compatible fix in revision 52436bba120d78f33bf7432c7147078b2de1b264

**Comment by SuperSandro2000** [comment]
I left a comment on the commit for a case which you might have missed.

**Pull request closed without merging**
